# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workouttracker.Groups'),
        ),
    ]
