# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0004_auto_20181112_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
    ]
