# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0006_auto_20181112_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouttracker.Exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutsummary',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutsummary',
            name='sets',
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouttracker.WorkoutSummary'),
        ),
    ]
