# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0007_auto_20181112_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
