# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0009_auto_20181112_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ManyToManyField(to='workouttracker.MuscleGroup'),
        ),
    ]
