# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0013_auto_20181113_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighthistory',
            options={'ordering': ['datetime'], 'verbose_name': 'Weight History', 'verbose_name_plural': 'Weight Histories'},
        ),
        migrations.AlterModelOptions(
            name='workoutsummary',
            options={'ordering': ['start'], 'verbose_name_plural': 'Workout Summaries'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_group', to='workouttracker.MuscleGroup'),
        ),
    ]
