# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouttracker', '0015_auto_20181113_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyareas',
            options={'ordering': ['name'], 'verbose_name_plural': 'Body Areas'},
        ),
        migrations.AddField(
            model_name='workoutsummary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
