# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0022_workoutdetail_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsummary',
            name='calculated_calories',
            field=models.IntegerField(default=0),
        ),
    ]
