# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0025_auto_20181114_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='intensity',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Moderate'), (3, 'High')], default=2),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='intensity',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Moderate'), (3, 'High')], default=2),
        ),
    ]
