# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0026_auto_20181115_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsummary',
            name='avg_heartrate',
            field=models.IntegerField(default=0),
        ),
    ]
