# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0027_workoutsummary_avg_heartrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='high_mets',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='exercise',
            name='low_mets',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='med_mets',
            field=models.FloatField(default=5),
        ),
    ]
