# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-17 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0035_auto_20181117_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouttracker.ExerciseType'),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 17, 10, 43, 549000)),
        ),
    ]
