# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0036_auto_20181117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsummary',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workouttracker.ExerciseType'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouttracker.ExerciseType'),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 12, 31, 6, 956000)),
        ),
    ]
