# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0037_auto_20181119_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 12, 32, 13, 993000)),
        ),
    ]
