# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0038_auto_20181119_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 16, 19, 45, 177000)),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='workouttracker.ExerciseType'),
            preserve_default=False,
        ),
    ]
