# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0041_auto_20181121_1138'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='exercisetype',
        #     name='order',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 14, 19, 24, 627000)),
        ),
    ]
