# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0042_auto_20181121_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='units',
            field=models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=5),
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='units',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=177),
        ),
        migrations.AlterField(
            model_name='weighthistory',
            name='units',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsummary',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
