# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workouttracker.Groups')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
