# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0002_groups_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='MuscleGroups',
        ),
    ]
