# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0003_auto_20181112_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuscleGroups',
            new_name='MuscleGroup',
        ),
    ]
