# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0008_workoutdetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdetail',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
