# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0010_auto_20181112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
