# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0014_auto_20181113_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workouttracker.BodyAreas'),
        ),
    ]
