# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0018_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cardio_daily_target',
            new_name='daily_target',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='strength_daily_target',
        ),
    ]
