# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0021_userprofile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='intensity',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Moderate'), (2, 'High')], default=1),
        ),
    ]
