# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0029_auto_20181115_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighthistory',
            name='bodyfat',
            field=models.FloatField(default=0),
        ),
    ]
