# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0031_auto_20181115_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
