# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-16 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0032_workoutdetail_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsummary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
