# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0033_auto_20181116_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
